### ISSUE TITLE
Type "SERIAL" does not exist'

### ISSUE THREAD

**Issue by itpooh** [LocusEnergy/sqlalchemy-vertica-python#4]
if create column:    id = Column(Integer, autoincrement=True)
error:Type "SERIAL" does not exist'

**Comment by lemeryfertitta** [comment]
Thanks for the issue. Noting that what this issue appears to be describing is that Vertica does not use SERIAL like Postgres, which is currently the base dialect for this library. This can be fixed in a future patch by overriding this behavior and using the IDENTITY column attribute. See https://my.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/AdministratorsGuide/Sequences/UsingAutoIncrementandIdentitySequences.htm for reference.

**Comment by jordiyeh** [comment]
Reading at the updated Postgresql 10 IDENTITY columns section dialect
sqlalchemy/dialects/postgresql/base.py

We can add the following code to swap SERIAL for IDENTITY as follows:


from sqlalchemy.schema import CreateColumn
from sqlalchemy.ext.compiler import compiles

@compiles(CreateColumn, 'vertica')
def use_identity(element, compiler, **kw):
    text = compiler.visit_create_column(element, **kw)
    text = text.replace("SERIAL", "IDENTITY(1,1)")
    return text

**Comment by lemeryfertitta** [comment]
@jordiyeh thanks for the implementation idea! If you're interested in getting this released, I'll happily review and package up any pull requests.

**Comment by lemeryfertitta** [comment]
Released in `0.4.2` thanks to @jordiyeh
